# Generated by Django 5.1 on 2024-11-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_about'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='AboutPage',
        ),
    ]
