# Generated by Django 5.1 on 2024-12-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_altura_alter_product_pzs_x_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ano_max',
            field=models.PositiveIntegerField(null=True, verbose_name='Año max'),
        ),
        migrations.AddField(
            model_name='product',
            name='ano_min',
            field=models.PositiveIntegerField(null=True, verbose_name='Año min'),
        ),
        migrations.AddField(
            model_name='product',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='modelo',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
