# Generated by Django 5.1 on 2024-12-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_ano_max_product_ano_min_product_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='empaquetadura',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
