# Generated by Django 5.1 on 2024-12-05 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_empaquetadura'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Producto',
        ),
        migrations.CreateModel(
            name='Equivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=25)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalences', to='products.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Equivalence',
        ),
    ]
