# Generated by Django 5.1 on 2024-12-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_marca_remove_producto_marca_remove_producto_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='nombre',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
