# Generated by Django 5.1 on 2024-12-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_marca_nombre_alter_modelo_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productomodelo',
            old_name='max_rango',
            new_name='ano',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ano_max',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ano_min',
        ),
        migrations.RemoveField(
            model_name='productomodelo',
            name='min_rango',
        ),
    ]
