# Generated by Django 5.1 on 2024-12-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productomodelo_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomodelo',
            name='ano',
            field=models.PositiveIntegerField(verbose_name='año'),
        ),
    ]
