# Generated by Django 5.0.10 on 2024-12-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productomodelo_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
    ]
