# Generated by Django 5.0.10 on 2024-12-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_producto_featured_producto_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='featured',
            new_name='destacado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='promotion',
        ),
        migrations.AddField(
            model_name='producto',
            name='promocion',
            field=models.BooleanField(default=False, verbose_name='Promoción'),
        ),
    ]
