# Generated by Django 5.0.10 on 2024-12-31 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_featured_producto_destacado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equivalencia',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias', to='products.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='linea',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='equivalencia',
            unique_together={('codigo', 'marca')},
        ),
    ]
