# Generated by Django 5.0.10 on 2024-12-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_equivalencia_producto_alter_producto_linea_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equivalencia',
            unique_together={('codigo', 'marca', 'producto')},
        ),
    ]
