# Generated by Django 5.0.10 on 2025-02-06 00:23

import products.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_producto_codigo_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='equivalencia',
            name='codigo_alt',
            field=models.GeneratedField(db_persist=True, expression=products.functions.RemoveHyphens(models.F('codigo')), output_field=models.CharField(max_length=50)),
        ),
    ]
