# Generated by Django 5.0.10 on 2025-02-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_equivalencia_codigo_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
